export const nombre = document.querySelector("#nombre")
export const email = document.querySelector("#email")
export const telefono = document.querySelector("#telefono")
export const empresa = document.querySelector("#empresa")
export const formulario = document.querySelector("#formulario")
export const contenedorLista = document.querySelector("#listado-clientes")